language: python

python:
  - "3.4"

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install psycopg2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source=pipsevents,booking,timetable,accounts --omit=../*migrations*,../*tests*,../*wsgi*,../*__init__* manage.py test

after_success:
  coveralls
